<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_Vereinzelung_Prozess" Id="{14ab87b7-a9dd-44e1-9b6e-ff56dbac8ca1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Vereinzelung_Prozess
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Physische eingänge 
//FB_Vereinzelung_EIngänge
//FB_Vereinzelung_logik
//FB_Vereinzelung_Ausgänge
//Physische Ausgänge]]></ST>
    </Implementation>
    <LineIds Name="FB_Vereinzelung_Prozess">
      <LineId Id="9" Count="4" />
    </LineIds>
  </POU>
</TcPlcObject>